"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from the .env file in the project root.
# After this line, os.environ.get('KEY') will find values from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

GROQ_API_KEY = os.environ.get('GROQ_API_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'tressie-lightless-remorsefully.ngrok-free.dev',
    os.environ.get('PYTHONANYWHERE_DOMAIN', '')
]

CSRF_TRUSTED_ORIGINS = [
    'https://tressie-lightless-remorsefully.ngrok-free.dev',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # needed for collectstatic on PythonAnywhere

# Auth redirects
# LOGIN_URL  — where @login_required sends unauthenticated users
# LOGIN_REDIRECT_URL  — where Django redirects after successful login (if no ?next=)
# LOGOUT_REDIRECT_URL — where Django redirects after logout
LOGIN_URL           = '/login/'
LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/login/'


# =============================================================================
# LOGGING
# =============================================================================
# Logging tells Django to print (or save to a file) information about what is
# happening inside your app. Think of it like the "black box" on an airplane:
# it records everything so you can go back and see what went wrong.
#
# Log Levels (from least to most serious):
#   DEBUG    → Very detailed, developer-only info ("Query took 2ms")
#   INFO     → Normal events ("User drashti05 logged in")
#   WARNING  → Something unusual but not broken ("Disk space low")
#   ERROR    → Something broke but the app is still running
#   CRITICAL → The app might be about to crash
# =============================================================================

LOGGING = {
    # version is always 1 — it's a required field Django expects
    'version': 1,

    # If True, Django's own default loggers are turned off.
    # We set False so Django's built-in warnings still show up.
    'disable_existing_loggers': False,

    # -------------------------------------------------------------------
    # FORMATTERS — define how each log line looks when printed
    # -------------------------------------------------------------------
    'formatters': {
        # "verbose" format: shows timestamp, log level, which file logged it, and the message
        'verbose': {
            'format': '[{asctime}] {levelname} {name} → {message}',
            'style': '{',        # {style} means we use {variable} syntax (not % syntax)
            'datefmt': '%d/%b/%Y %H:%M:%S',  # e.g. 25/Feb/2026 10:43:00
        },
        # "simple" format: just the level and message — less clutter for quick reading
        'simple': {
            'format': '{levelname} → {message}',
            'style': '{',
        },
    },

    # -------------------------------------------------------------------
    # HANDLERS — where do the logs actually go?
    # -------------------------------------------------------------------
    'handlers': {
        # "console" handler: prints logs to the terminal (where you run the server)
        'console': {
            'class': 'logging.StreamHandler',  # StreamHandler = output to terminal
            'formatter': 'verbose',            # use the detailed format defined above
        },
    },

    # -------------------------------------------------------------------
    # LOGGERS — which parts of the code get logged, and at what level?
    # -------------------------------------------------------------------
    'loggers': {

        # ── Our own app code ──────────────────────────────────────────
        # Catches anything logged with: import logging; logger = logging.getLogger('tracker')
        'tracker': {
            'handlers': ['console'],
            'level': 'DEBUG',      # Show everything — DEBUG and above
            'propagate': False,    # Don't pass it up to the root logger (avoids duplicates)
        },

        # ── Our accounts app ─────────────────────────────────────────
        'accounts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },

        # ── Django's own internals ────────────────────────────────────
        # Shows internal Django events like URL resolution, template loading, etc.
        'django': {
            'handlers': ['console'],
            'level': 'INFO',       # INFO and above only (DEBUG would be too noisy)
            'propagate': True,
        },

        # ── Database queries ──────────────────────────────────────────
        # Shows every SQL query Django runs — great for spotting slow queries
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',    # Set to DEBUG to see every SQL query (very verbose!)
            'propagate': False,
        },

        # ── Security events ───────────────────────────────────────────
        # Logs CSRF failures, bad requests, etc.
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },

        # ── HTTP Requests ─────────────────────────────────────────────
        # Logs every incoming request: method, path, response code
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',    # WARNING = only log 4xx/5xx errors, not every 200 OK
            'propagate': False,
        },
    },
}

