# Generated by Django 6.0.2 on 2026-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_application_options_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_suggestion',
            field=models.TextField(blank=True),
        ),
    ]
