# Generated by Django 6.0.2 on 2026-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_application_ai_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_chat',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
